### ISSUE TITLE
Pester test not executed when -fixture is set in a describe command

### ISSUE THREAD

**Issue by ambsoerensen** [PowerShell/Operation-Validation-Framework#17]
Pester tests are not executed when a describe block have the -fixture parameter specified with the name. 

the function "Get-TestFromScript" returns the text value of token right before the first token of the type 'GroupStart'. Without regard to the type of that previous token. 

In this case the returned string == '-Fixture'.

**Comment by devblackops** [comment]
Fixed in #25
