### ISSUE TITLE
CI?

### ISSUE THREAD

**Issue by davidwallis** [PowerShell/Operation-Validation-Framework#21]
Is there any CI configured on this project to push changes to the gallery? I want to make use of the parameters option and doesn't seem to be present :)

Whats the process for release? Gallery lists 1.0.1 as the version so I am assuming someone isn't updating this?

**Comment by devblackops** [comment]
@davidwallis3101 I'm in the process of refactoring the project structure. With that will be integration with AppVeyor and then hopefully more frequent releases to the gallery.

**Comment by davidwallis** [comment]
What's your timescales and do you need any assistance? 




On Mon, Jun 26, 2017 at 5:33 PM +0100, "Brandon Olin" <notifications@github.com> wrote:












@davidwallis3101 I'm in the process of refactoring the project structure. With that will be integration with AppVeyor and then hopefully more frequent releases to the gallery.

**Comment by devblackops** [comment]
For this work, no assistance necessary but thanks. If you find bugs or want to suggest new features please put in issues/PRs for them.

Hopefully in the next few days I'll have the project structure and AppVeyor integration for CI done. There won't be automatic deploys to PSGallery with that. Right now, @JamesWTruher is the only one who can deploy to PSGallery. Hopefully I'll get access to push this module as well.

In the meantime, you can manually clone the repository and import the module.

**Comment by devblackops** [comment]
@davidwallis3101 PR https://github.com/PowerShell/Operation-Validation-Framework/pull/22 has been created for the project restructure.

**Comment by davidwallis** [comment]
@devblackops  ok, I have cloned your repo that the PR was done from and have a couple of issues / suggestions.

Add [CmdletBinding()] to function Get-TestFromScript and then add at line 81 write-verbose ("Processing File {0}" -f $scriptPath)

This will then allow us to use -verbose (at least on this function to see which file is being processed) which helped me track down this issue:

![image](https://user-images.githubusercontent.com/13855486/27580000-466abf34-5b21-11e7-9721-4fadce82e9d3.png)

I'll do a bit more digging and post back once I have debugged it further.

**Comment by davidwallis** [comment]
forget that its https://github.com/PowerShell/Operation-Validation-Framework/issues/15
