### ISSUE TITLE
Error generated when using Invoke-OperationValidation with the -testFilePath parameter

### ISSUE THREAD

**Issue by mikefrobbins** [PowerShell/Operation-Validation-Framework#3]
When the operational tests are specified in a standalone ps1 file (without a module), an error is generated if the path to the ps1 file is not deep enough. The problem occurs on line 393 in the OperationValidation,psm1 file (in the Convert-TestResult function):

$Module = $result.Path.split([io.path]::DirectorySeparatorChar)[-4]

The error message that's generated:

PS C:> Invoke-OperationValidation -testFilePath C:\tests\sqlserver.tests.ps1 -Verbose
VERBOSE: Performing the operation "Invoke-OperationValidation" on target "C:\tests\sqlserver.tests.ps1".
New-OperationValidationResult : Cannot bind argument to parameter 'Module' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\OperationValidation\OperationValidation.psm1:395 char:47
-         New-OperationValidationResult -Module $Module -Name $TestName ...
-                                               ~~~~~~~
  - CategoryInfo          : InvalidData: (:) [New-OperationValidationResult], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-OperationValidationResult

PS C:>

It runs without issue when specifying a deeper path:

PS C:> Invoke-OperationValidation -testFilePath C:\tests\SQLServer\sqlserver.tests.ps1 -Verbose
VERBOSE: Performing the operation "Invoke-OperationValidation" on target "C:\tests\SQLServer\sqlserver.tests.ps1".

   Module: C:

Result Name

---

Passed Simple Validation of a SQL Server::Should be listening on port 1433

PS C:>

As you can see in this scenario, the drive letter is specified as the module name result. I would expect the module information to be omitted unless the -ModuleName parameter is specified when calling the Invoke-OperationValidation function.

**Comment by JamesWTruher** [comment]
good catch - appropriate action? create a sensible default if it's not associated with a module, or be sure that $null is ok?

**Comment by mikefrobbins** [comment]
It almost seems like Convert-TestResult needs a module parameter so Invoke-OperationValidation can feed the module name to it when the ModuleName parameter is specified. New-OperationValidationResult would also have to be modified so the Module parameter is not mandatory.

**Comment by larssb** [comment]
Hi there....

Have this exact error. Also, I wasn't aware that it is a requirement that a .Tests.ps1 file is accompanied by a .psm1 file. The current documentation do not mention anything about. At least not as far as I can see anywhere.
I quickly tried to call the full-direct-path to the .Tests.ps1 file and things are working. But. It would be fantastic to get this fixed. 
How active is this repository, I'm thinking, if I did a PR and tried to fix it would someone on here give it a glance or two?

Thank you and looking forward to hear from you.

**Comment by ronhowe** [comment]
I'm getting this error too.

**Comment by devblackops** [comment]
@larssb @ronhowe @mikefrobbins This should FINALLY be fixed in 3fde749bad57c205dd2e21b6a2939df71fdf38e8.
