### ISSUE TITLE
Module release upcoming?

### ISSUE THREAD

**Issue by lholman** [PowerShell/Operation-Validation-Framework#30]
I notice the current version of OVF published to PowershellGallery is 1.0.1, however there have been two significant branches merged in to master with no corresponding releases, is there any plan to publish these changes soon?
Most notably I'm finding OVF is pretty unusable with Pester 4.1.1 due to the OVF `-IncludePesterOutput` parameter not supporting the Pester deprecated use of its `-Quiet` parameter, this fix is included in master and it's a shame it can't be easily consumed by people already using OVF.
I'm happy to help set-up a CI pipeline if required.

**Comment by devblackops** [comment]
@JamesWTruher The current version in master should be pushed to PSGallery. Can you do this or add me as an owner in PSGallery so I can push it?

**Comment by JamesWTruher** [comment]
I'll follow up with our gallery folks to see how I can transfer ownership in the gallery so you can publish!

**Comment by devblackops** [comment]
Thanks @JamesWTruher! Here is the doc on how to add an owner in PSGallery.

https://docs.microsoft.com/en-us/powershell/gallery/psgallery/managing-item-owners

**Comment by JamesWTruher** [comment]
@devblackops hopefully I did this right - you should have an email if I did, otherwise, you'll need to send me your username for the gallery

**Comment by devblackops** [comment]
Got it @JamesWTruher. Thanks!

**Comment by devblackops** [comment]
@lholman Just published `v1.1.0`. I'll be making a few changes soon to add support for macOS/Linux as well.

https://www.powershellgallery.com/packages/OperationValidation/1.1.0

**Comment by davidwallis** [comment]
Just checked back to see if this had been done and happy to see it has :) thanks all.
