### ISSUE TITLE
Version Comparison error

### ISSUE THREAD

**Issue by davidwallis** [PowerShell/Operation-Validation-Framework#39]
Check is performed for the version number.. 

## Current Behavior

Could not compare "5.1.16299.1004" to "5". Error: "Cannot convert value "5" to type "System.Version". Error: "Version string portion was too short or too long.""
At C:\Program Files\WindowsPowerShell\Modules\OperationValidation\1.2.0\Public\Get-OperationValidation.ps1:223 char:21
+                 if ($PSVersionTable.PSVersion -ge 5) {
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : ComparisonFailure

## Steps to Reproduce (for bugs)

1. PS Version 5.1.16299.1004 - windows 10
2. invoke validation
3.
4.

## Your Environment

* 1.2.0
* PS Version 5.1.16299.1004 - windows 10

Will do more debugging to establish a possible fix

**Comment by davidwallis** [comment]
Argh.. Another thing that appears fixed in the repo but not in the gallery.. Is it due a release - this is a little frustrating :)

**Comment by devblackops** [comment]
Sorry @davidwallis3101. Looks like version 1.2.1 which fixed that issue with PR https://github.com/PowerShell/Operation-Validation-Framework/pull/36 was never released to PSGallery...until now. Please update to that version and try again. https://www.powershellgallery.com/packages/OperationValidation/1.2.1
