### ISSUE TITLE
Purpose of the OVF

### ISSUE THREAD

**Issue by megamorf** [PowerShell/Operation-Validation-Framework#4]
Hey guys,

I saw @mikefrobbins mention this framework on twitter but I must admit that I don't really understand its purpose (in comparison to vanilla pester tests). Could you explain what the benefit of using this framework is and what you envision it to be in the medium-term.

Thanks in advance :-)

**Comment by megamorf** [comment]
So?

**Comment by JamesWTruher** [comment]
sorry, for some reason my notifications were buried in some email rule.

This is really about organization of tests. If you project into the future, a _host_ of Pester tests will be on any given system. The OVF allows for those tests to be organized and executed in a consistent manner. If you look at PowerShell from a philosophical perspective, we do that a lot (think our approved verbs). The OVF asserts a place for diagnostics as part of a module; as well as a way to determine (and retrieve) those tests, and can execute only those tests in a consistent manner. 
For example, if you were to just run `Invoke-Pester` you would certainly run more tests than you would want, unless you managed your tests somewhat carefully. At the end of the day, this module isn't the important bit - _Pester_ is that. This is just a way to manage those tests in a consistent manner. 
Jeffrey Snover made the comparison to steak and salt - Pester is the steak, and OVF is the salt. You just need a little salt, but it can really help.
