### ISSUE TITLE
What's the story for running OVF against multiple environments?

### ISSUE THREAD

**Issue by redoz** [PowerShell/Operation-Validation-Framework#5]
I'm in the process of setting up Pester/OVF to monitor our production environment. But I'd also like to be able to run them against out Test environment, but I see no means for passing arguments through the Invoke-OperationValidation function.

**Comment by devblackops** [comment]
I agree. The framework should support passing parameter/arguments to Pester tests. I have a proposal in issue #6 for that. I'll probably put in a PR to add that soon.

**Comment by devblackops** [comment]
Closing this as Pester script arguments can now be passed in to `Invoke-OperationValidation` as of PR #12
